## ASBD LAB 9 - CED19I027 - N. SREE DHYUTI

In [13]:
# CED19I027 - N. SREE DHYUTI - ASBD LAB9
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

## Implement the Decision Tree model on the dataset we have discussed in the class and also test the same on a benchmark dataset (preferably binary classification dataset). Also explore the packages that are suitable to display the decision tree.

In [14]:
iris = load_iris()
print(type(iris['data']))
print(iris['data'][0:10])
print(iris['target'][0:10])
X = iris.data
y = iris.target

<class 'numpy.ndarray'>
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
[0 0 0 0 0 0 0 0 0 0]


In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
dtc = DecisionTreeClassifier()
dtc.fit(X_train, y_train)
y_pred = dtc.predict(X_test)
print(y_pred)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0 0 0 2 1 1 0 0]


In [16]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 1.0


In [17]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np

data = np.array([[29, 2, 0, 1], [28, 2, 0, 0], [32, 2, 0, 1],
                         [41, 1, 0, 1], [42, 0, 1, 1], [43, 0, 1, 0],[34, 0, 1, 0], 
                         [25, 1, 0, 1], [24, 0, 1, 1],[44, 1, 1, 1],
                         [22, 1, 1, 0], [36, 1, 0, 0], [37, 2, 1, 1],[49, 1, 0, 0]])
target = np.array([0,0,1,1,1,0,1,0,1,1,1,1,1,0])
X=data
y=target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
dtc = DecisionTreeClassifier()
dtc.fit(X_train, y_train)
y_pred = dtc.predict(X_test)
print(y_pred)

[0 1 0]


In [18]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.6666666666666666
